-- Schema used by the FastAPI service in SAT/backend.
-- Apply this only to a new Supabase project. Existing projects should be
-- migrated deliberately after backing up their data.

create extension if not exists pgcrypto;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 120),
  email text not null unique check (char_length(email) between 3 and 320),
  password_hash text not null,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamp with time zone not null default now()
);

create table if not exists public.analysis_history (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  sentence text not null,
  s_expression text not null,
  tree_json jsonb not null,
  sentence_type text not null default 'Unknown',
  created_at timestamp with time zone not null default now()
);

create table if not exists public.error_reports (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  sentence text not null,
  description text not null,
  analysis_result_json jsonb,
  status text not null default 'open' check (status in ('open', 'reviewing', 'resolved')),
  created_at timestamp with time zone not null default now()
);

-- The API uses a server-only Supabase secret key. Keep RLS enabled so no
-- browser client can read these tables accidentally; service-role requests
-- remain the only intended data access path.
alter table public.users enable row level security;
alter table public.analysis_history enable row level security;
alter table public.error_reports enable row level security;

revoke all on table public.users, public.analysis_history, public.error_reports from anon, authenticated;

create index if not exists idx_analysis_history_user_id_created_at
  on public.analysis_history(user_id, created_at desc);
create index if not exists idx_error_reports_user_id_created_at
  on public.error_reports(user_id, created_at desc);
create index if not exists idx_error_reports_status
  on public.error_reports(status);
